# Generated by Django 3.1.8 on 2021-04-22 05:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bio',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], default=''),
            preserve_default=False,
        ),
    ]
